topic_folders = [
    ['4-h-youth', '4-H and Youth'],     ['agriculture', 'Agriculture'],     ['community-development', 'Community Development'],     ['families-children', 'Families and Children'],     ['food-nutrition', 'Food and Nutrition'],     ['horticulture-gardening', 'Horticulture and Gardening'],     ['natural-resources', 'Natural Resources'], 
]

def getCountyWeather(county_name):

    url = "http://wwwagwx.ca.uky.edu/cgi-bin/getcast_www_pa.ldm?%s"

    county_links = {
        'Adams' : ['Adams',],
        'Allegheny' : ['Allegheny',],
        'Armstrong' : ['Armstrong',],
        'Beaver' : ['Beaver',],
        'Bedford' : ['Bedford',],
        'Berks' : ['Berks',],
        'Blair' : ['Blair',],
        'Bradford' : ['Bradford',],
        'Bucks' : ['Bucks',],
        'Butler' : ['Butler',],
        'Cambria' : ['Cambria',],
        'Cameron' : ['Cameron',],
        'Carbon' : ['Carbon',],
        'Chester' : ['Chester',],
        'Clarion' : ['Clarion',],
        'Clearfield' : ['Clearfield',],
        'Columbia' : ['Columbia',],
        'Crawford' : ['Crawford',],
        'Cumberland' : ['Cumberland',],
        'Dauphin' : ['Dauphin',],
        'Delaware' : ['Delaware',],
        'Elk' : ['Elk',],
        'Fayette' : ['Fayette',],
        'Forest' : ['Forest',],
        'Franklin' : ['Franklin',],
        'Fulton' : ['Fulton',],
        'Greene' : ['Greene',],
        'Huntingdon' : ['Huntingdon',],
        'Indiana' : ['Indiana',],
        'Jefferson' : ['Jefferson',],
        'Juniata' : ['Juniata',],
        'Lackawanna' : ['Lackawanna',],
        'Lancaster' : ['Lancaster',],
        'Lawrence' : ['Lawrence',],
        'Lebanon' : ['Lebanon',],
        'Lehigh' : ['Lehigh',],
        'Luzerne' : ['Luzerne',],
        'Mckean' : ['Mckean',],
        'Mercer' : ['Mercer',],
        'Mifflin' : ['Mifflin',],
        'Monroe' : ['Monroe',],
        'Montgomery' : ['Montgomery',],
        'Montour' : ['Montour',],
        'Northampton' : ['Northampton',],
        'Centre' : ['Northern Centre', 'Southern Centre',],
        'Clinton' : ['Northern Clinton', 'Southern Clinton',],
        'Erie' : ['Northern Erie', 'Southern Erie',],
        'Lycoming' : ['Northern Lycoming', 'Southern Lycoming',],
        'Northumberland' : ['Northumberland',],
        'Perry' : ['Perry',],
        'Philadelphia' : ['Philadelphia',],
        'Pike' : ['Pike',],
        'Potter' : ['Potter',],
        'Schuylkill' : ['Schuylkill',],
        'Snyder' : ['Snyder',],
        'Somerset' : ['Somerset',],
        'Sullivan' : ['Sullivan',],
        'Susquehanna' : ['Susquehanna',],
        'Tioga' : ['Tioga',],
        'Union' : ['Union',],
        'Venango' : ['Venango',],
        'Warren' : ['Warren',],
        'Washington' : ['Washington',],
        'Wayne' : ['Wayne', 'Southern Wayne',],
        'Westmoreland' : ['Westmoreland',],
        'Wyoming' : ['Wyoming',],
        'York' : ['York',],
        'Keystone' : ['Centre',],
    }
    
    if county_links.get(county_name):
        return [('%s County Weather and Climate Synopsis' % x, url % x.replace(' ', '+')) for x in county_links[county_name]]
